### ISSUE TITLE
Latest commit from moltin/cart break this package

### ISSUE THREAD

**Issue by rained23** [moltin/laravel-cart#42]
Hi, after running composer update,  I am unable to run my application.

Below is the error

```
Class Moltin\Cart\Storage\LaravelSession contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Moltin\Cart\StorageInterface::findAll, 
Moltin\Cart\StorageInterface::destroyAll)
```

Is it possible to not tagging laravel-cart to `dev-master` ?
I am unable to revert back because this package require the failing build.

**Comment by outrunthewolf** [comment]
Apologies. We've reverted the cart package to its previous state. Has this fixed things for you?

**Comment by rained23** [comment]
@outrunthewolf , yes its fixed now. :+1:

**Comment by outrunthewolf** [comment]
Awesome.
