### ISSUE TITLE
Latest merge break Laravel 4.2

### ISSUE THREAD

**Issue by rained23** [moltin/laravel-cart#46]
Hi,

Commit 470b2650 break laravel 4.2, if the future release are suppose for L5, is it possible to create tags for Laravel ~4.* ?

Regards,
Rain

**Comment by emamalias** [comment]
+1 I'm having the same issue

**Comment by rained23** [comment]
for now I make a fork of this repo and tag the working commit for L4 with v4.0 
and use VCS in my composer.

**Comment by outrunthewolf** [comment]
We've tagged off, let me know if that works?

**Comment by rained23** [comment]
@outrunthewolf , the tag has fixed this issue.

thanks.
