### ISSUE TITLE
Laravel 4.2 composer update error

### ISSUE THREAD

**Issue by aquinotgr00** [moltin/laravel-cart#49]
hello guys, i had problem over here, i'm using laravel 4.2 currently
i tried to include 
"moltin/cart": "dev-master"
then run composer update, and it's work
aftter that i add 

'Moltin\Cart\CartServiceProvider', and 
'Cart'            => 'Moltin\Cart\Facade',

but when i run composer update it says 

{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Class 'Moltin\Cart\CartServiceProvider' not found"

**Comment by SvenRtbg** [comment]
Don't mix up the package names! "moltin/cart" is not "moltin/laravel-cart".
