### ISSUE TITLE
Error Composer Require

### ISSUE THREAD

**Issue by josebispo** [moltin/laravel-cart#64]
Hi ,  congrats for plugin, I'm did try install via composer your  plugin but ins't possible , please verify or composer components,  thank's

the trouble :-1:  
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - moltin/laravel-cart v5.0.1 requires moltin/cart dev-master -> no matching package found.
    - moltin/laravel-cart v5.0 requires moltin/cart dev-master -> no matching package found.
    - Installation request for moltin/laravel-cart ^5.0 -> satisfiable by moltin/laravel-cart[v5.0, v5.0.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by terdelyi** [comment]
Did you set `"minimum-stability":` `"dev"` in your root composer.json file?
